engines:
  eslint:
    enabled: true
    exclude_paths:
      - docs/**
  csslint:
    enabled: true
    exclude_paths:
      - docs/**
  eslint-jsx:
    enabled: true
    exclude_paths:
      - docs/**
  stylelint:
    enabled: true
    exclude_paths:
      - docs/**
