name: Testing Workflow

on:
  pull_request:
    branches: main

jobs:
  enforce-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: ESLint check
        run: npm run format
      - name: Prettier check
        run: npm run prettier:fix

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Run E2E tests
        run: npm run test:e2e
